version: 0.2

phases:
  pre_build:
    commands:
      - yum install -y git-lfs
      - GIT_LFS_SKIP_SMUDGE=1 git clone --depth 1 https://github.com/awslabs/osml-model-runner.git lib/osml-model-runner
      - cd lib/osml-model-runner && git lfs pull && pip install -r test/integ/requirements.txt pytest

  build:
    commands:
      - npm run integ:model-runner
